/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cortes;

import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class My_Banking_System extends javax.swing.JFrame {

    /**
     * Creates new form BANKO
     */
    
    String user = "root";
    String pass = "";
    String connString = "jdbc:mysql://localhost:3306/bank_system";
    
    int ReferenceNumber = 0;
    String ReferenceName = "";
    int ReferenceBalance = 0;
    
    int limit = 0;
    int id = 0;
    
    
    public My_Banking_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void updateTable(){
     DefaultTableModel model =  (javax.swing.table.DefaultTableModel) My_Table.getModel();
     
        int count = 1;
        model.setRowCount(0); 
         try{
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank_system", "root", "");
        Statement query = conn.createStatement();
        String q = "select * from transaction limit "+limit+","+limit+10+"";
        ResultSet result = query.executeQuery(q);
        while(result.next()){
            Object[] data = {count, result.getInt("bank_account"),result.getString("customer_name").toString(),result.getInt("desposit"), result.getInt("widthdraw"), result.getInt("current_balance"),result.getString("date").toString() };
             model.addRow(data);
             count++;
        }
       
         }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error on update Table: "+e);
         }
        
    }
    private void clear(){
        OpenBank_AccountNo.setText("");
        OpenBank_CustomerName.setText("");
        OpenBank_BalanceField.setText("");
        OpenBank_SearchField.setText("");
        id = 0;
        OpenBank_SpecifyBranch.setSelectedIndex(0);
        OpenBank_SpecifySex.setSelectedIndex(0);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        OpenBank_AccountNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        OpenBank_CustomerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        OpenBank_SpecifySex = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        OpenBank_SpecifyBranch = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        OpenBank_BalanceField = new javax.swing.JTextField();
        btnOpenAcc = new javax.swing.JButton();
        btnModifyAcc = new javax.swing.JButton();
        btnDeleteAcc = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        OpenBank_SearchField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        BankTrans_SearchField = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        My_Table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Withdraw_CustomerNameField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Withdraw_BalanceField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Withdraw_AmountField = new javax.swing.JTextField();
        btnWithdraw = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Withdraw_AccountNoSearch = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Deposit_CustomerNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Deposit_BalanceField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Deposit_AmountField = new javax.swing.JTextField();
        btnDeposit = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        Deposit_SearchField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 7));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Account No: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Customer Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Sex:");

        OpenBank_SpecifySex.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        OpenBank_SpecifySex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Branch:");

        OpenBank_SpecifyBranch.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        OpenBank_SpecifyBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OpenBank_SpecifyBranch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpenBank_SpecifyBranchItemStateChanged(evt);
            }
        });
        OpenBank_SpecifyBranch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                OpenBank_SpecifyBranchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                OpenBank_SpecifyBranchFocusLost(evt);
            }
        });
        OpenBank_SpecifyBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBank_SpecifyBranchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Initial Balance:");

        OpenBank_BalanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBank_BalanceFieldActionPerformed(evt);
            }
        });

        btnOpenAcc.setBackground(new java.awt.Color(0, 0, 204));
        btnOpenAcc.setFont(new java.awt.Font("Goudy Stout", 1, 10)); // NOI18N
        btnOpenAcc.setText("Open");
        btnOpenAcc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 6));
        btnOpenAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenAccActionPerformed(evt);
            }
        });

        btnModifyAcc.setBackground(new java.awt.Color(0, 0, 204));
        btnModifyAcc.setFont(new java.awt.Font("Goudy Stout", 1, 10)); // NOI18N
        btnModifyAcc.setText("Modify");
        btnModifyAcc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 6));
        btnModifyAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyAccActionPerformed(evt);
            }
        });

        btnDeleteAcc.setBackground(new java.awt.Color(0, 0, 204));
        btnDeleteAcc.setFont(new java.awt.Font("Goudy Stout", 1, 10)); // NOI18N
        btnDeleteAcc.setText("Delete");
        btnDeleteAcc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 6));
        btnDeleteAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 0, 204));
        btnClear.setFont(new java.awt.Font("Goudy Stout", 3, 10)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 6));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 153, 0)));

        jLabel7.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        jLabel7.setText("OPEN BANK ACCOUNT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jLabel1.setText("Enter Account Number:");

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 6));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(OpenBank_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(OpenBank_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OpenBank_SpecifyBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpenBank_SpecifySex, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpenBank_BalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnOpenAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModifyAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(OpenBank_AccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OpenBank_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenBank_AccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpenBank_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenBank_BalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenBank_SpecifySex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnOpenAcc)
                    .addComponent(btnModifyAcc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenBank_SpecifyBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnClear)
                    .addComponent(btnDeleteAcc))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Open Account", jPanel1);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Search Acct No:");

        BankTrans_SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankTrans_SearchFieldActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 153, 0));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton12.setText("SEARCH");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 153, 0));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setText("SHOW ALL");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        My_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Bank Account", "Customer Name", "Desposit", "Widthdrawal", "Current Balance", "Date"
            }
        ));
        jScrollPane1.setViewportView(My_Table);
        if (My_Table.getColumnModel().getColumnCount() > 0) {
            My_Table.getColumnModel().getColumn(1).setMinWidth(100);
        }

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jButton2.setText("Next");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jButton3.setText("Prev");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel19.setBackground(new java.awt.Color(102, 102, 102));
        jPanel19.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 153, 0)));

        jLabel21.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel21.setText("BANK TRANSACTIONS");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(43, 43, 43))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(BankTrans_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankTrans_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bank Transaction", jPanel4);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Customer Name:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Current Balance:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Amount:");

        btnWithdraw.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnWithdraw.setText("Withdraw");
        btnWithdraw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 6));
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jButton11.setText("Clear");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 153, 0)));

        jLabel20.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel20.setText(" WITHDRAW MONEY");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton9.setFont(new java.awt.Font("Goudy Stout", 3, 14)); // NOI18N
        jButton9.setText("Search");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 6));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Enter Account No:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Withdraw_AccountNoSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Withdraw_AccountNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Withdraw_AmountField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(Withdraw_BalanceField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Withdraw_CustomerNameField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(54, 54, 54)
                                .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Withdraw_CustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Withdraw_BalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(btnWithdraw))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Withdraw_AmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Withdraw Money", jPanel3);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Customer name:");

        Deposit_CustomerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deposit_CustomerNameFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Current Balance:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Amount:");

        btnDeposit.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnDeposit.setText("Desposit");
        btnDeposit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 6));
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jButton8.setText("Clear");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 153, 0)));

        jLabel19.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel19.setText("deposit money");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(42, 42, 42))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jButton6.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jButton6.setText("Search");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 7));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Enter Account No: ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Deposit_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(Deposit_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Deposit_CustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Deposit_AmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Deposit_BalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Deposit_CustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Deposit_BalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Deposit_AmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Deposit Money", jPanel2);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 255, 255)));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel8.setText("BANKING SYSTEM");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        OpenBank_SpecifySex.removeAllItems();
        OpenBank_SpecifySex.addItem("Male");
        OpenBank_SpecifySex.addItem("Female");
        OpenBank_SpecifySex.addItem("E-male");
        OpenBank_SpecifySex.addItem("G-male");
        OpenBank_SpecifySex.addItem("I'm a Mechanic");
        OpenBank_SpecifyBranch.removeAllItems();
        OpenBank_SpecifyBranch.addItem("BRANCH NI BRIOL");
        OpenBank_SpecifyBranch.addItem("BRANCH KO");
        OpenBank_SpecifyBranch.addItem("BRANCH WWW");
        
        if (OpenBank_SpecifyBranch.getSelectedItem().equals("BRANCH NI BRIOL")){
            OpenBank_BalanceField.setText("1000");
        }
        else if (OpenBank_SpecifyBranch.getSelectedItem().equals("BRANCH KO")){
            OpenBank_BalanceField.setText("0");
        }
        else if (OpenBank_SpecifyBranch.getSelectedItem().equals("BRANCH WWW")){
            OpenBank_BalanceField.setText("5000");
        }
        
        updateTable();
   
    }//GEN-LAST:event_formWindowOpened

    private void depositData(){
         try{
             Connection conn = DriverManager.getConnection(connString, user, pass);
             PreparedStatement stmp = conn.prepareStatement("UPDATE accounts set balance = ? where id = ?");
             int depos = Integer.parseInt(Deposit_AmountField.getText());
             int bal = ReferenceBalance + depos;
             stmp.setInt(1, bal);
             stmp.setInt(2, id);
             stmp.executeUpdate();
             ReferenceNumber = 0;
             Deposit_AmountField.setText("");
             Deposit_BalanceField.setText("");
             ReferenceName = "";
             ReferenceBalance = 0;
             Deposit_CustomerNameField.setText("");
             Deposit_SearchField.setText("");
             id = 0;
             JOptionPane.showMessageDialog(rootPane, "YOU HAVE SUCCESSFULLY DEPOSITED YOUR MONEY !!");
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(rootPane, "Error on deposit: " + e);
         }
    }
    
     private void depositDataWith(){
         try{
             Connection conn = DriverManager.getConnection(connString, user, pass);
             PreparedStatement stmp = conn.prepareStatement("UPDATE accounts set balance = ? where id = ?");
             int depos = Integer.parseInt(Withdraw_AmountField.getText());
             if(depos > ReferenceBalance){
                JOptionPane.showMessageDialog(rootPane, "Lagpas na");
                return;
             }
             int bal = ReferenceBalance - depos < 1 ? 0 : ReferenceBalance - depos;
             stmp.setInt(1, bal);
             stmp.setInt(2, id);
             stmp.executeUpdate();
             ReferenceNumber = 0;
             Withdraw_AmountField.setText("");
             Withdraw_BalanceField.setText("");
             ReferenceName = "";
             ReferenceBalance = 0;
             Withdraw_CustomerNameField.setText("");
             Withdraw_AccountNoSearch.setText("");
             id = 0;
             JOptionPane.showMessageDialog(rootPane, "YOU HAVE SUCCESSFULLY WITHDRAWN YOUR MONEY !!");
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(rootPane, "Error on withdraw: " + e);
         }
    }
    private void Deposit_CustomerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deposit_CustomerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Deposit_CustomerNameFieldActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Withdraw_AccountNoSearch.setText("");
        Withdraw_CustomerNameField.setText("");
        Withdraw_BalanceField.setText("");
        Withdraw_AmountField.setText("");
        id = 0;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnOpenAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenAccActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = DriverManager.getConnection(connString, user, pass);
            PreparedStatement stmp = conn.prepareStatement("INSERT INTO accounts (account_number, customer_name, sex, branch, balance) values(?,?,?,?,?)");
            stmp.setInt(1, Integer.parseInt(OpenBank_AccountNo.getText()));
            stmp.setString(2, OpenBank_CustomerName.getText());
            stmp.setString(3, OpenBank_SpecifySex.getSelectedItem().toString());
            stmp.setString(4, OpenBank_SpecifyBranch.getSelectedItem().toString());
            stmp.setInt(5, Integer.parseInt(OpenBank_BalanceField.getText()));
            stmp.executeUpdate();
            stmp.close();
            conn.close();
            clear();
            JOptionPane.showMessageDialog(rootPane, "YOU SUCCESSFULLY OPENED AN ACCOUNT");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR ! UNABLE TO OPEN ACCOUNT ON: "+e);
        }
    }//GEN-LAST:event_btnOpenAccActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(OpenBank_SearchField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "PLEASE FILL OFF THE TEXTFIELD");
            return;
        }
        try{
          Integer.parseInt(OpenBank_SearchField.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Enter a number");
            return;
        }
        try{
             Connection conn = DriverManager.getConnection(connString, user, pass);
             Statement query = conn.createStatement();
             ResultSet res = query.executeQuery("SELECT * from accounts where account_number = "+OpenBank_SearchField.getText());
             while(res.next()){
             if(res.getString("customer_name").toString().length() > 0){
                JOptionPane.showMessageDialog(rootPane, "SEARCH SUCCESS !!, RESULT FOUND !");
                id = res.getInt("id");
                OpenBank_CustomerName.setText(res.getString("customer_name").toString());
                OpenBank_AccountNo.setText(String.valueOf(res.getInt("account_number")));
                if(res.getString("sex").toString().equals("Male")){
                    OpenBank_SpecifySex.setSelectedIndex(0);
                }
                if(res.getString("sex").toString().equals("Female")){
                    OpenBank_SpecifySex.setSelectedIndex(1);
                }
                if (res.getString("sex").toString().equals("E-male")){
                    OpenBank_SpecifySex.setSelectedIndex(2);
                }
                if (res.getString("sex").toString().equals("G-male")){
                    OpenBank_SpecifySex.setSelectedIndex(3);
                }
                if (res.getString("sex").toString().equals("I'm a Mechanic")){
                    OpenBank_SpecifySex.setSelectedIndex(4);
                }
                 if(res.getString("branch").toString().equals("BRANCH NI BRIOL")){
                    OpenBank_SpecifyBranch.setSelectedIndex(0);
                }
                  if(res.getString("branch").toString().equals("BRANCH KO")){
                    OpenBank_SpecifyBranch.setSelectedIndex(1);
                }
                  if(res.getString("branch").toString().equals("BRANCH WWW")){
                    OpenBank_SpecifyBranch.setSelectedIndex(2);
                }  
                  OpenBank_BalanceField.setText(String.valueOf(res.getInt("balance")));
                return;
             }
             }
              JOptionPane.showMessageDialog(rootPane, "ACCOUNT NUMBER DOES NOT EXIST");
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR ON SEARCH ACCOUNT: "+e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
             if(Deposit_SearchField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "PLEASE FILL OFF THE TEXTFIELD");
            return;
        }
        try{
          Integer.parseInt(Deposit_SearchField.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Enter a number");
            return;
        }
        try{
             Connection conn = DriverManager.getConnection(connString, user, pass);
             Statement query = conn.createStatement();
             ResultSet res = query.executeQuery("SELECT * from accounts where account_number = "+Deposit_SearchField.getText());
             while(res.next()){
             if(res.getString("customer_name").toString().length() > 0){
                JOptionPane.showMessageDialog(rootPane, "SEARCH SUCCESS !!, RESULT FOUND !");
                Deposit_CustomerNameField.setText(res.getString("customer_name").toString());
                Deposit_BalanceField.setText(String.valueOf(res.getInt("balance")));
                Deposit_BalanceField.setEditable(false);
                Deposit_CustomerNameField.setEditable(false);
                id = res.getInt("id");
                ReferenceName = res.getString("customer_name").toString();
                ReferenceNumber = res.getInt("account_number");
                ReferenceBalance = res.getInt("balance");
                return;
             }
             }
              JOptionPane.showMessageDialog(rootPane, "ACCOUNT NUMBER DOES NOT EXIST");
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR ON SEARCH ACCOUNT: "+e);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnModifyAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyAccActionPerformed
        // TODO add your handling code here:
          try{
             Connection conn = DriverManager.getConnection(connString, user, pass);
             PreparedStatement stmp = conn.prepareStatement("UPDATE accounts set account_number = ?, customer_name = ?, sex = ?, branch = ?, balance = ? where id = ?");
               stmp.setInt(1, Integer.parseInt(OpenBank_AccountNo.getText()));
            stmp.setString(2, OpenBank_CustomerName.getText());
            stmp.setString(3, OpenBank_SpecifySex.getSelectedItem().toString());
            stmp.setString(4, OpenBank_SpecifyBranch.getSelectedItem().toString());
            stmp.setInt(5, Integer.parseInt(OpenBank_BalanceField.getText()));
            stmp.setInt(6, id);
            stmp.executeUpdate();
            stmp.close();
            conn.close();
            clear();
            JOptionPane.showMessageDialog(rootPane, "UPDATED INFORMATION SUCCESSFULLY");
             
             }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR ON SEARCH ACCOUNT: "+e);
        }
    }//GEN-LAST:event_btnModifyAccActionPerformed

    private void btnDeleteAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccActionPerformed
        // TODO add your handling code here:
        if(id == 0){
            JOptionPane.showMessageDialog(rootPane, "YOU HAVE TO SEARCH AN ACCOUNT FIRST");
            return;
        }
          try{
             Connection conn = DriverManager.getConnection(connString, user, pass);
             PreparedStatement stmp = conn.prepareStatement("DELETE FROM accounts where id = ?");
             stmp.setInt(1, id);
             stmp.executeUpdate();
             JOptionPane.showMessageDialog(rootPane, "YOU HAVE SUCCESSFULLY DELETED AN ACCOUNT!");
             clear();
              }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR UNKNOWN ACCOUNT: "+e);
              }
    }//GEN-LAST:event_btnDeleteAccActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
         if(id == 0){
            JOptionPane.showMessageDialog(rootPane, "YOU HAVE TO SEARCH AN ACCOUNT FIRST");
            return;
        }
        Date dt = new Date();
        SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy");
         String curDate = format.format(dt);
         try{
             Connection conn = DriverManager.getConnection(connString, user, pass);
             PreparedStatement stmp = conn.prepareStatement("INSERT INTO transaction (bank_account, customer_name, desposit, widthdraw, current_balance, date) VALUES (?,?,?,?,?,?)");
             stmp.setInt(1, ReferenceNumber);
             stmp.setString(2, ReferenceName);
             stmp.setInt(3, Integer.parseInt(Deposit_AmountField.getText()));
             stmp.setInt(4, 0);
             stmp.setInt(5, ReferenceBalance);
             stmp.setString(6, curDate);
             stmp.executeUpdate();
             stmp.close();
             depositData();
             updateTable();
          }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR ON SEARCH ACCOUNT: "+e);
              }
        
    }//GEN-LAST:event_btnDepositActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Deposit_SearchField.setText("");
        Deposit_CustomerNameField.setText("");
        Deposit_BalanceField.setText("");
        Deposit_AmountField.setText("");
        id = 0;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
          if(id == 0){
            JOptionPane.showMessageDialog(rootPane, "YOU HAVE TO SEARCH AN ACCOUNT FIRST");
            return;
        }
        Date dt = new Date();
        SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy");
         String curDate = format.format(dt);
         try{
             Connection conn = DriverManager.getConnection(connString, user, pass);
             PreparedStatement stmp = conn.prepareStatement("INSERT INTO transaction (bank_account, customer_name, desposit, widthdraw, current_balance, date) VALUES (?,?,?,?,?,?)");
             stmp.setInt(1, ReferenceNumber);
             stmp.setString(2, ReferenceName);
             stmp.setInt(4, Integer.parseInt(Withdraw_AmountField.getText()));
             stmp.setInt(3, 0);
             stmp.setInt(5, ReferenceBalance);
             stmp.setString(6, curDate);
             stmp.executeUpdate();
             stmp.close();
             depositDataWith();
             updateTable();
          }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR ON WITHDRAW ACCOUNT: "+e);
              }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          if(Withdraw_AccountNoSearch.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "PLEASE FILL OFF THE TEXTFIELD");
            return;
        }
        try{
          Integer.parseInt(Withdraw_AccountNoSearch.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Enter a number");
            return;
        }
        try{
             Connection conn = DriverManager.getConnection(connString, user, pass);
             Statement query = conn.createStatement();
             ResultSet res = query.executeQuery("SELECT * from accounts where account_number = "+Withdraw_AccountNoSearch.getText());
             while(res.next()){
             if(res.getString("customer_name").toString().length() > 0){
                JOptionPane.showMessageDialog(rootPane, "SEARCH SUCCESS !!, RESULT FOUND !");
                Withdraw_CustomerNameField.setText(res.getString("customer_name").toString());
                Withdraw_BalanceField.setText(String.valueOf(res.getInt("balance")));
                Withdraw_BalanceField.setEditable(false);
                Withdraw_CustomerNameField.setEditable(false);
                id = res.getInt("id");
                ReferenceName = res.getString("customer_name").toString();
                ReferenceNumber = res.getInt("account_number");
                ReferenceBalance = res.getInt("balance");
                return;
             }
             }
              JOptionPane.showMessageDialog(rootPane, "THIS ACCOUNT NUMBER IS UNKNOWN");
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR ON SEARCH ACCOUNT: "+e);
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model =  (javax.swing.table.DefaultTableModel) My_Table.getModel();
     
        int count = 1;
        model.setRowCount(0); 
         if (BankTrans_SearchField.getText().equals("")){
             JOptionPane.showMessageDialog(null, "PLEASE FILL OFF THE ENTRY SEARCH !!");
         }else{
            try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank_system", "root", "");
                Statement query = conn.createStatement();
                String q = "select * from transaction where bank_account = "+BankTrans_SearchField.getText();
                ResultSet result = query.executeQuery(q);
                while(result.next()){
                    Object[] data = {count, result.getInt("bank_account"),result.getString("customer_name").toString(),result.getInt("desposit"), result.getInt("widthdraw"), result.getInt("current_balance"),result.getString("date").toString() };
                    model.addRow(data);
                    count++;
                }
       
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "ERROR ON UPDATE TABLE: "+e);
            }
         }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        updateTable();
        BankTrans_SearchField.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
       limit = limit + 10;
       updateTable();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(limit < 10){
            JOptionPane.showMessageDialog(rootPane, "THIS IS ALREADY THE VERY FIRST PAGE");
        }else{
            limit = limit - 10;
            updateTable();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void BankTrans_SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankTrans_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankTrans_SearchFieldActionPerformed

    private void OpenBank_SpecifyBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBank_SpecifyBranchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OpenBank_SpecifyBranchActionPerformed

    private void OpenBank_BalanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBank_BalanceFieldActionPerformed
        // TODO add your handling code here:
        //OpenBank_BalanceField.setEditable(false);
        
    }//GEN-LAST:event_OpenBank_BalanceFieldActionPerformed

    private void OpenBank_SpecifyBranchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OpenBank_SpecifyBranchFocusLost
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_OpenBank_SpecifyBranchFocusLost

    private void OpenBank_SpecifyBranchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpenBank_SpecifyBranchItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OpenBank_SpecifyBranchItemStateChanged

    private void OpenBank_SpecifyBranchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OpenBank_SpecifyBranchFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OpenBank_SpecifyBranchFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(My_Banking_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(My_Banking_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(My_Banking_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(My_Banking_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new My_Banking_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BankTrans_SearchField;
    private javax.swing.JTextField Deposit_AmountField;
    private javax.swing.JTextField Deposit_BalanceField;
    private javax.swing.JTextField Deposit_CustomerNameField;
    private javax.swing.JTextField Deposit_SearchField;
    private javax.swing.JTable My_Table;
    private javax.swing.JTextField OpenBank_AccountNo;
    private javax.swing.JTextField OpenBank_BalanceField;
    private javax.swing.JTextField OpenBank_CustomerName;
    private javax.swing.JTextField OpenBank_SearchField;
    private javax.swing.JComboBox<String> OpenBank_SpecifyBranch;
    private javax.swing.JComboBox<String> OpenBank_SpecifySex;
    private javax.swing.JTextField Withdraw_AccountNoSearch;
    private javax.swing.JTextField Withdraw_AmountField;
    private javax.swing.JTextField Withdraw_BalanceField;
    private javax.swing.JTextField Withdraw_CustomerNameField;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteAcc;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnModifyAcc;
    private javax.swing.JButton btnOpenAcc;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
